import { app, BrowserWindow, autoUpdater, ipcMain, shell } from 'electron'
import path from 'path'
import url from 'url'
import log from 'electron-log'
import installExtension, { REACT_DEVELOPER_TOOLS } from 'electron-devtools-installer'
require('./services/autoUpdater')
import { getLastUser } from './services/sqlite'
import { capture, client } from './services/analytics'

const lastUser = getLastUser()
capture({
  distinctId: lastUser,
  event: 'app launched',
  properties: {
    appVersion: app.getVersion(),
  },
})

var openUrl = ''

if (process.defaultApp) {
  if (process.argv.length >= 2) {
    app.setAsDefaultProtocolClient('journal', process.execPath, [path.resolve(process.argv[1])])
  }
} else {
  app.setAsDefaultProtocolClient('journal')
}

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

// Env
// process.env.NODE_ENV = 'development'

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  // eslint-disable-line global-require
  app.quit()
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1600,
    width: 1800,
    titleBarStyle: 'customButtonsOnHover',
    trafficLightPosition: { x: 16, y: 16 },
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      spellcheck: true,
    },
  })

  ipcMain.on('electron-reload', async () => {
    mainWindow.reload()
  })

  mainWindow.on('resized', () => {
    console.log('resized')
    capture({
      distinctId: getLastUser(),
      event: 'app resized',
      properties: mainWindow.getBounds(),
    })
  })

  mainWindow.on('maximize', () => {
    console.log('maximize')
    capture({
      distinctId: getLastUser(),
      event: 'app maximize',
    })
  })

  mainWindow.on('minimize', () => {
    console.log('minimize')
    capture({
      distinctId: getLastUser(),
      event: 'app minimize',
    })
  })

  mainWindow.on('enter-full-screen', () => {
    console.log('enter-full-screen')
    capture({
      distinctId: getLastUser(),
      event: 'app enter-full-screen',
    })
  })

  mainWindow.once('ready-to-show', () => {
    mainWindow.show()

    // Handle open from url when app was closed
    if (openUrl) {
      mainWindow.webContents.send('open-url', openUrl)
      openUrl = ''
    }

    // Handle Update downloaded
    autoUpdater.on('update-downloaded', () => {
      console.log('update-downloaded')
      log.info('update-downloaded')
      mainWindow.webContents.send('update-downloaded')
    })
  })

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)

  // Open the DevTools.
  mainWindow.webContents.openDevTools()
  installExtension(REACT_DEVELOPER_TOOLS)
    .then((name) => console.log(`Added Extension:  ${name}`))
    .catch((err) => console.log('An error occurred: ', err))

  mainWindow.webContents.on('context-menu', (event: any, params: any) => {
    console.log('context-menu event')

    mainWindow.webContents.send('electron-handleSpellCheck', params)
    // const menu = new Menu()

    // // Add each spelling suggestion
    // for (const suggestion of params.dictionarySuggestions) {
    //   menu.append(
    //     new MenuItem({
    //       label: suggestion,
    //       click: () => mainWindow.webContents.replaceMisspelling(suggestion),
    //     })
    //   )
    // }

    // // Allow users to add the misspelled word to the dictionary
    // if (params.misspelledWord) {
    //   menu.append(
    //     new MenuItem({
    //       label: 'Add to dictionary',
    //       click: () =>
    //         mainWindow.webContents.session.addWordToSpellCheckerDictionary(params.misspelledWord),
    //     })
    //   )
    // }

    // menu.popup()
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('before-quit', () => {
  console.log('before-quit')
  capture({
    distinctId: getLastUser(),
    event: 'app close',
  })
})

app.on('will-quit', () => {
  client.shutdown()
})

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

// Handle the protocol
app.on('open-url', (event, url) => {
  const win = BrowserWindow.getAllWindows()[0]
  if (win) {
    // Handle open from url when app is opened
    win.webContents.send('open-url', url)
  } else {
    // If app is closed/no windows, save url for when app opens
    openUrl = url
  }
})

// Open links in the browser
app.on('web-contents-created', (event, contents) => {
  contents.on('will-navigate', (event, navigationUrl) => {
    const parsedUrl = new url.URL(navigationUrl)
    const isDev = parsedUrl.host == 'localhost:3000'
    if (!isDev && ['https:', 'http:', 'mailto:'].includes(parsedUrl.protocol)) {
      event.preventDefault()
      shell.openExternal(navigationUrl)
    }
  })
})

app.commandLine.appendSwitch('ignore-certificate-errors')

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
